server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称
  client:
    #false表示不向注册中心注册自己。
    register-with-eureka: false
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。
      defaultZone: http://eureka7002.com:7002/eureka/
#  server:
#    enable-self-preservation: false  #开启自我保护开关，缺省默认是true
#    eviction-interval-timer-in-ms: 2000 #续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms），当微服务发现挂了以后，扫描的时间